//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.5

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, Default, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "compression_leafs")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub collection_id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub merkle_tree: String,
    #[sea_orm(column_type = "Text")]
    pub tree_authority: String,
    #[sea_orm(column_type = "Text")]
    pub tree_delegate: String,
    #[sea_orm(column_type = "Text")]
    pub leaf_owner: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub asset_id: Option<String>,
    pub created_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
