//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.5

pub use super::{
    certified_collections::Entity as CertifiedCollections,
    collection_mints::Entity as CollectionMints, editions::Entity as Editions,
};
